### ISSUE TITLE
require phpunit in composer.json as require-dev

### ISSUE THREAD

**Issue by tobiasgraeber** [olifolkerd/convertor#16]
see: https://getcomposer.org/doc/03-cli.md#init

Please require the composer package in require-dev section instead require section (as now) - otherwise all the unneeded dependencies of phpunit are per default part of your and others projects (like mine, if i install your package by composer install,...)

thanks!

**Comment by FWidm** [comment]
Ah forgot about that when doing the pull-request, so it should be:
```json
{
    "name": "olifolkerd/convertor",
    "description": "An easy to use PHP unit conversion library.",
    "license": "MIT",
    "authors": [
        {
            "name": "Oli Folkerd",
            "email": "oliver.folkerd@gmail.com"
        }
    ],
    "require-dev": { <-- appended '-dev' 
        "phpunit/phpunit": "^6.2"
    },
    "autoload": {
        "psr-4": {
            "Olifolkerd\\Convertor\\": "src/"
        }
    },
    "minimum-stability": "dev"
}
```

Unfortunately even my old PR wasn't merged yet so I do have low hopes for this to get pulled either :(.

**Comment by olifolkerd** [comment]
Hey @FWidm 

Your old pull request did get merged, i would be happy to accept any pull request to fix this.

Cheers

Oli

**Comment by FWidm** [comment]
Ah i meant the fix to the readme that is still hanging, I'll create a PR with the change - would be great :) Good to know you're still active here 👍 
Edit: see #15 I was unable to make a fresh PR as my repo requires the readme change as well. 

Output for `composer install --no-dev`:
```
Loading composer repositories with package information
Updating dependencies
Writing lock file
Generating autoload files
```
=> PHPUnit is now gone from the production ready dir.

**Comment by tobiasgraeber** [comment]
Nice! Thanks!

**Comment by olifolkerd** [comment]
All merged :D
