### ISSUE TITLE
Support composer

### ISSUE THREAD

**Issue by b3nl** [olifolkerd/convertor#2]
I think, you should provide a more modern way to include this lib.

**Comment by olifolkerd** [comment]
if you have any specific methods in mind i would be more that happy to add them.

Which package managers would you like to see used?

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

Great idea! will get composer support in in the next few days.

Oli

**Comment by FWidm** [comment]
As an FYI you can now use the project by specifying the repo in your composer json like this:
```
...
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/olifolkerd/convertor"
    }
  ],
  "require": {
    "olifolkerd/convertor": "dev-master"
   }
...
```
