### ISSUE TITLE
How to display/handle error validation on empty units?

### ISSUE THREAD

**Issue by justzuhri** [olifolkerd/convertor#7]
$simpleConvertor->to("ft"); //returns converted value

If the user put wrong unit or leave the unit empty, eg: $simpleConvertor->to("fttttt"); display this "you have entered wrong or empty unit" or redirect to 404 page. How to do this?

Im getting so many error logs: 

[05-Aug-2017 23:06:58 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unit Not Set' in /public_html/Convertor.php:1020
Stack trace:
#0 /public_html/xxx.php(3): Convertor->to('')
#1 /public_html/xxxx.php(176): include('/xxx...')
#2 {main}
  thrown in /public_html/Convertor.php on line 1020

**Comment by olifolkerd** [comment]
You need to catch the exception:

```php
try {
   $simpleConvertor->to("fttttt"); 
} catch (Exception $e) {
   //handle exception
   $msg = $e->getMessage(); get exception message
}
```
I hope that helps,

Cheers

Oli
